
package Interface;

import javax.swing.JFrame;

public class GDmain extends javax.swing.JFrame {

   private String User;
   private int maquyen;
    public GDmain(String Users,int maquyens) {
        this.setSize(800, 800);
        initComponents();
        if(maquyens==1){
            jmiTaouser.setEnabled(false);
            jmDanhmuc.setEnabled(false);
            jmiLop.setEnabled(false);
            jmiSV.setEnabled(false);
            jmiGV.setEnabled(false);
            jmidetai.setEnabled(false);
            jmiTiendo.setEnabled(false);
            jmiKQNT.setEnabled(false);
        }
        User=Users;
        maquyen=maquyens;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmHethong = new javax.swing.JMenu();
        jmiTaouser = new javax.swing.JMenuItem();
        jmiDangnhap = new javax.swing.JMenuItem();
        jmiDangxuat = new javax.swing.JMenuItem();
        jmidoimk = new javax.swing.JMenuItem();
        jmDanhmuc = new javax.swing.JMenu();
        jmiKhoa = new javax.swing.JMenuItem();
        jmiLop = new javax.swing.JMenuItem();
        jmiSV = new javax.swing.JMenuItem();
        jmiGV = new javax.swing.JMenuItem();
        jmidetai = new javax.swing.JMenuItem();
        jmQLDT = new javax.swing.JMenu();
        jmiDKDT = new javax.swing.JMenuItem();
        jmiTiendo = new javax.swing.JMenuItem();
        jmiKQNT = new javax.swing.JMenuItem();
        jmtim = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmthongke = new javax.swing.JMenu();
        jmiKQ = new javax.swing.JMenuItem();
        jmhelp = new javax.swing.JMenu();
        jmiHuongdan = new javax.swing.JMenuItem();
        jmiThongtin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setTitle("Quản lý Đề tài Nghiên Cứu Khoa Học");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame1.setVisible(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2020-12-01 164317.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Chương trình Quản lý Đề tài Nghiên Cứu Khoa Học");
        jLabel2.setToolTipText("");

        jmHethong.setText("Hệ thống");

        jmiTaouser.setText("Tạo User");
        jmiTaouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTaouserActionPerformed(evt);
            }
        });
        jmHethong.add(jmiTaouser);

        jmiDangnhap.setText("Đăng nhập");
        jmiDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDangnhapActionPerformed(evt);
            }
        });
        jmHethong.add(jmiDangnhap);

        jmiDangxuat.setText("Đăng xuất");
        jmiDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDangxuatActionPerformed(evt);
            }
        });
        jmHethong.add(jmiDangxuat);

        jmidoimk.setText("Đổi mật khẩu");
        jmidoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmidoimkActionPerformed(evt);
            }
        });
        jmHethong.add(jmidoimk);

        jMenuBar1.add(jmHethong);

        jmDanhmuc.setText("Danh mục");

        jmiKhoa.setText("Danh mục khoa");
        jmiKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKhoaActionPerformed(evt);
            }
        });
        jmDanhmuc.add(jmiKhoa);

        jmiLop.setText("Danh mục lớp");
        jmiLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLopActionPerformed(evt);
            }
        });
        jmDanhmuc.add(jmiLop);

        jmiSV.setText("Danh mục sinh viên");
        jmiSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSVActionPerformed(evt);
            }
        });
        jmDanhmuc.add(jmiSV);

        jmiGV.setText("Danh mục giảng viên");
        jmiGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGVActionPerformed(evt);
            }
        });
        jmDanhmuc.add(jmiGV);

        jmidetai.setText("Danh mục đề tài");
        jmidetai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmidetaiActionPerformed(evt);
            }
        });
        jmDanhmuc.add(jmidetai);

        jMenuBar1.add(jmDanhmuc);

        jmQLDT.setText("Quản lý đề tài");

        jmiDKDT.setText("Đăng ký đề tài");
        jmiDKDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDKDTActionPerformed(evt);
            }
        });
        jmQLDT.add(jmiDKDT);

        jmiTiendo.setText("Cập nhật tiến độ");
        jmiTiendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTiendoActionPerformed(evt);
            }
        });
        jmQLDT.add(jmiTiendo);

        jmiKQNT.setText("Kết quả nghiệm thu");
        jmiKQNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKQNTActionPerformed(evt);
            }
        });
        jmQLDT.add(jmiKQNT);

        jMenuBar1.add(jmQLDT);

        jmtim.setText("Tìm kiếm");
        jmtim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtimActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Thông Tin Sinh Viên");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmtim.add(jMenuItem1);

        jMenuBar1.add(jmtim);

        jmthongke.setText("Thống kê");

        jmiKQ.setText("Kết quả nghiệm thu");
        jmiKQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKQActionPerformed(evt);
            }
        });
        jmthongke.add(jmiKQ);

        jMenuBar1.add(jmthongke);

        jmhelp.setText("Help");
        jmhelp.setToolTipText("");

        jmiHuongdan.setText("Hướng dẫn");
        jmhelp.add(jmiHuongdan);

        jmiThongtin.setText("Thông tin phần mềm");
        jmhelp.add(jmiThongtin);

        jMenuBar1.add(jmhelp);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 570, 350);
        try {
            jInternalFrame1.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLopActionPerformed
        new  Lop(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiLopActionPerformed

    private void jmiGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGVActionPerformed
        new  GV(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiGVActionPerformed

    private void jmiTaouserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTaouserActionPerformed
        new  TaoUser().setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiTaouserActionPerformed

    private void jmiDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDangnhapActionPerformed
        new  GDlogin().setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiDangnhapActionPerformed

    private void jmidoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmidoimkActionPerformed
        new  DoiMK(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmidoimkActionPerformed

    private void jmiSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSVActionPerformed
        new  SV(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiSVActionPerformed

    private void jmiKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKhoaActionPerformed
        new  Khoa(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiKhoaActionPerformed

    private void jmidetaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmidetaiActionPerformed
        new  Detai(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmidetaiActionPerformed

    private void jmiTiendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTiendoActionPerformed
        new  Tiendo(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiTiendoActionPerformed

    private void jmiKQNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKQNTActionPerformed
        new  KQNT(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiKQNTActionPerformed

    private void jmtimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtimActionPerformed
          new Tim(User,maquyen).setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jmtimActionPerformed

    private void jmiKQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKQActionPerformed
        new  TKKQNT(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiKQActionPerformed

    private void jmiDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDangxuatActionPerformed
        new  GDlogin().setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiDangxuatActionPerformed

    private void jmiDKDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDKDTActionPerformed
        new  Dangky(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jmiDKDTActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         new  Tim(User,maquyen).setVisible(true);// sang man hinh khac 
        this.dispose();// AN man hinh hien tai 
    }//GEN-LAST:event_jMenuItem1ActionPerformed
 
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu jmDanhmuc;
    private javax.swing.JMenu jmHethong;
    private javax.swing.JMenu jmQLDT;
    private javax.swing.JMenu jmhelp;
    private javax.swing.JMenuItem jmiDKDT;
    private javax.swing.JMenuItem jmiDangnhap;
    private javax.swing.JMenuItem jmiDangxuat;
    private javax.swing.JMenuItem jmiGV;
    private javax.swing.JMenuItem jmiHuongdan;
    private javax.swing.JMenuItem jmiKQ;
    private javax.swing.JMenuItem jmiKQNT;
    private javax.swing.JMenuItem jmiKhoa;
    private javax.swing.JMenuItem jmiLop;
    private javax.swing.JMenuItem jmiSV;
    private javax.swing.JMenuItem jmiTaouser;
    private javax.swing.JMenuItem jmiThongtin;
    private javax.swing.JMenuItem jmiTiendo;
    private javax.swing.JMenuItem jmidetai;
    private javax.swing.JMenuItem jmidoimk;
    private javax.swing.JMenu jmthongke;
    private javax.swing.JMenu jmtim;
    // End of variables declaration//GEN-END:variables
}
