/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Interface.PreSenter.GiaoDucModel;
import Interface.PreSenter.GiaoDucPreSenter;
import Interface.PreSenter.GiaoDucView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Penguin
 */
public class Khoa extends javax.swing.JFrame
implements GiaoDucView,ActionListener{
    private GiaoDucPreSenter gd;
    private String User;
    private int maquyen;
    public Khoa(String U,int ma) {
        initComponents();
        gd=new GiaoDucPreSenter(this);
        HanlerEvents();
        User=U;
        maquyen=ma;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtenhkhoa = new javax.swing.JTextField();
        txttruongkhoa = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Khoa");
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cập nhật danh mục khoa");

        jLabel3.setText("Tên khoa");

        jLabel4.setText("Trưởng khoa");

        jLabel5.setText("Số điện thoại khoa");

        btnthem.setText("Thêm");

        btnsua.setText("Sửa");

        btnxoa.setText("Xóa");

        btnhuy.setText("Hủy");

        btntimkiem.setText("Tìm Kiếm");

        btnback.setText("back");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnthem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtenhkhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(txttruongkhoa)
                                .addComponent(txtsdt))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnsua)
                                .addGap(18, 18, 18)
                                .addComponent(btnxoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnhuy))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txttimkiem))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(btntimkiem))
                    .addComponent(btnback))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem))
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtenhkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttruongkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnhuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnback))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtenhkhoa;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttruongkhoa;
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnSucess() {
        JOptionPane.showMessageDialog(rootPane, "Sucess","Thông Báo",1);
        
    }

    @Override
    public void OnError() {
         JOptionPane.showMessageDialog(rootPane, "Failed","Lỗi/Failed",1);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btnthem){
            String ten=txtenhkhoa.getText().toString().trim();
            String truongkhoa=txttruongkhoa.getText().toString().trim();
            String sdt=txtsdt.getText().toString().trim();
            if(ten.length()>0 && truongkhoa.length()>0 && sdt.length()>0){
                gd.HanlerInsertKhoa(ten, truongkhoa, sdt);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Không Để Trống !","Thông  Báo",1);
            }
        }
        else if(e.getSource()==btntimkiem){
            String ten = txttimkiem.getText().toString().trim();// tim kiem theo ten khoa
            if(ten.length()>0){
                gd.HanlerTimKiemKhoa(ten);
            }
        }else if(e.getSource()==btnsua){
            String ten=txtenhkhoa.getText().toString().trim();// cap nhat theo then khoa
            String truongkhoa=txttruongkhoa.getText().toString();
            String sdt=txtsdt.getText().toString().trim();
            if(ten.length()>0){
                 gd.HanlerUpdateKhoa(ten, truongkhoa, sdt);
             }
        }else if(e.getSource()==btnhuy){
            txtenhkhoa.setText(null);
            txttruongkhoa.setText(null);
            txtsdt.setText(null);
        }else if(e.getSource()==btnxoa){
            String ten=txtenhkhoa.getText().toString().trim();// xoa theo ten khoa
            if(ten.length()>0){
                gd.HanlerDeleteKhoa(ten);
            }
        }
        else if(e.getSource()==btnback){
            new GDmain(User,maquyen).setVisible(true);
            this.dispose();
        }
    }

    private void HanlerEvents() {
        btnthem.addActionListener(this);
        btntimkiem.addActionListener(this);
        btnsua.addActionListener(this);
        btnxoa.addActionListener(this);
        btnhuy.addActionListener(this);
         btnback.addActionListener(this);
    }

    @Override
    public void getDataTimKiem(String ten, String truongkhoa, String sdt) {
        txtenhkhoa.setText(ten);
        txttruongkhoa.setText(truongkhoa);
        txtsdt.setText(sdt);
    }

    @Override
    public void getDataKhoa(int makhoa, String ten, String truongkhoa, String sdt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataTimKiemLop(int makhoa, String tenlop) {
      
    }

    @Override
    public void getDataLop(int makhoa, int malop, String tenlop) {
       
    
    }

    
    @Override
    public void getDataTimKiemGV(int makhoa, String tengv, String ngaysinh, String hocvi, int gioitinh,  String diachi, String sdt, String email, String chuyennganh) {
         throw new UnsupportedOperationException("Not supported yet."); 
    }

    @Override
    public void getDataTimKiemTienDo(String maBC, String madetai, String thoigianbaocao, String tiendothuchien, String nguoibaocao, String ghichu) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataTimKiemNghiemThu(String mant, String madetai, String tgnt, String tgbd, String tgkt, float kinhphi, String ketluan) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataTimKiemSinhVien(int malop, String ten, String ngaysinh, int gioitinh, String diachi, String sdt, String email) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
