/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.PreSenter.GiaoDucPreSenter;
import Interface.PreSenter.GiaoDucView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Penguin
 */
public class KQNT extends javax.swing.JFrame
 implements ActionListener,GiaoDucView{

    private GiaoDucPreSenter gd;
    private String Users;
    private int maquyens;
    public KQNT(String U,int m) {
        initComponents();
        gd=new GiaoDucPreSenter(this);
        gd.HanlerReadDataDeTai();
        HanlerEvents();
        Users=U;
        maquyens=m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        madetaicombo = new javax.swing.JComboBox<>();
        tgnt = new javax.swing.JTextField();
        kinhphi = new javax.swing.JTextField();
        tgbd = new javax.swing.JTextField();
        tgkt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kl = new javax.swing.JTextArea();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        txtmadetai = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Kết quả nghiệm thu");
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cập nhật kết quả nghiệm thu");

        jLabel3.setText("Mã đề tài:");

        jLabel4.setText("Thời gian nghiệm thu:");

        jLabel5.setText("Kinh phí");

        jLabel6.setText("Thời gian bắt đầu:");

        jLabel7.setText("Thời gian kết thúc:");

        jLabel8.setText("Kết luận:");

        tgnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgntActionPerformed(evt);
            }
        });

        kl.setColumns(20);
        kl.setRows(5);
        jScrollPane1.setViewportView(kl);

        btnthem.setText("Thêm");

        btnsua.setText("Sửa");

        btnxoa.setText("Xóa");

        btnhuy.setText("Hủy");

        btntimkiem.setText("Tim Kiem");

        btnback.setText("Back");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(kinhphi, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tgnt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(madetaicombo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(btnthem)
                                .addGap(94, 94, 94)
                                .addComponent(btnsua)))))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgkt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgbd, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnhuy)
                        .addGap(59, 59, 59))))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(txtmadetai, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(btntimkiem)
                        .addGap(305, 305, 305))))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(btnback)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tgbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(madetaicombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(tgnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(kinhphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnhuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtmadetai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntimkiem)
                .addGap(19, 19, 19)
                .addComponent(btnback))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tgntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgntActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kinhphi;
    private javax.swing.JTextArea kl;
    private javax.swing.JComboBox<String> madetaicombo;
    private javax.swing.JTextField tgbd;
    private javax.swing.JTextField tgkt;
    private javax.swing.JTextField tgnt;
    private javax.swing.JTextField txtmadetai;
    // End of variables declaration//GEN-END:variables

   

    @Override
    public void OnSucess() {
        JOptionPane.showMessageDialog(rootPane, "Sucess","Thong Bao",1);
    }

    @Override
    public void OnError() {
        JOptionPane.showMessageDialog(rootPane, "Sucess","Failed",1);
    }

    @Override
    public void getDataTimKiem(String ten, String truongkhoa, String sdt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataKhoa(int makhoa, String ten, String truongkhoa, String sdt) {
       madetaicombo.addItem(String.valueOf(makhoa));
    }

    @Override
    public void getDataTimKiemLop(int makhoa, String tenlop) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataLop(int makhoa, int malop, String tenlop) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    @Override
    public void getDataTimKiemGV(int makhoa, String ten, String ngaysinh, String hocvi, int gioitinh, String diachi, String sdt, String email, String chuyennganh) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataTimKiemTienDo(String maBC, String madetai, String thoigianbaocao, String tiendothuchien, String nguoibaocao, String ghichu) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataTimKiemNghiemThu(String mant, String madetai, String tgnts, String tgbds, String tgkts, float kp, String ketluan) {
        madetaicombo.setSelectedItem(madetai);
        tgnt.setText(tgnts);
        tgbd.setText(tgbds);
        tgkt.setText(tgkts);
        kinhphi.setText(String.valueOf(kp));
        kl.setText(ketluan);
        
        
    }
     @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btnback){
            new GDmain(Users,maquyens).setVisible(true);
           this.dispose();
        }else if(e.getSource()==btnthem){
             SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");// Nam- thang- Ngay
                String madetai=madetaicombo.getSelectedItem().toString().trim();
            String thoigiannghiemthu="";
            String thoigianbatdau="";
            String thoigianketthuc="";
            
            try {
              thoigiannghiemthu=tgnt.getText().toString().trim();
                sdf.parse(thoigiannghiemthu);   
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai Định Dạng : yyyy-MM-dd","Thong bao",1);
            }
            try {
               thoigianbatdau=tgbd.getText().toString().trim();
                sdf.parse(thoigianbatdau);
                
                
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai Định Dạng : yyyy-MM-dd","Thong bao",1);
            }
            try {
                thoigianketthuc=tgkt.getText().toString().trim();
                sdf.parse(thoigianketthuc);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai Định Dạng : yyyy-MM-dd","Thong bao",1);
            }
            float kinhphis=Float.parseFloat(kinhphi.getText().toString().trim());
            String ketluan=kl.getText().toString().trim();
            if(thoigianbatdau.length()>0 && thoigiannghiemthu.length()>0 && thoigianketthuc.length()>0
                    && ketluan.length()>0){
                gd.HanlerInsertNghiemThu(madetai, thoigiannghiemthu,thoigianbatdau,thoigianketthuc, kinhphis, ketluan);
            
            }else{
                JOptionPane.showMessageDialog(rootPane, "Khong De trong","Thong Bao",1);
            }
            
        
                    
        }else if(e.getSource()==btntimkiem){
            String madetai=txtmadetai.getText().toString().trim();// tim kiem theo ten sv
            gd.HanlerTimKiemNghiemThu(madetai);
        }else if(e.getSource()==btnxoa){
           String madetai=txtmadetai.getText().toString().trim();// tim kiem theo ten sv
            gd.HanlerDeleteNghiemThu(madetai);
        }else if(e.getSource()==btnhuy){
           tgbd.setText(null);tgkt.setText(null);
           tgnt.setText(null);kl.setText(null);
           kinhphi.setText(null);
              
        }else if(e.getSource()==btnsua){
              SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");// Nam- thang- Ngay
                String madetai=madetaicombo.getSelectedItem().toString().trim();
            String thoigiannghiemthu="";
            String thoigianbatdau="";
            String thoigianketthuc="";
            
            try {
              thoigiannghiemthu=tgnt.getText().toString().trim();
                sdf.parse(thoigiannghiemthu);   
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai Định Dạng : yyyy-MM-dd","Thong bao",1);
            }
            try {
               thoigianbatdau=tgbd.getText().toString().trim();
                sdf.parse(thoigianbatdau);
                
                
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai Định Dạng : yyyy-MM-dd","Thong bao",1);
            }
            try {
                thoigianketthuc=tgkt.getText().toString().trim();
                sdf.parse(thoigianketthuc);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai Định Dạng : yyyy-MM-dd","Thong bao",1);
            }
            float kinhphis=Float.parseFloat(kinhphi.getText().toString().trim());
            String ketluan=kl.getText().toString().trim();
            if(thoigianbatdau.length()>0 && thoigiannghiemthu.length()>0 && thoigianketthuc.length()>0
                    && ketluan.length()>0){
                gd.HanlerUpdateNghiemThu(madetai, thoigiannghiemthu,thoigianbatdau,thoigianketthuc, kinhphis, ketluan);
            
            }else{
                JOptionPane.showMessageDialog(rootPane, "Khong De trong","Thong Bao",1);
            }
            
        }
        
    }
     private void HanlerEvents() {
         btntimkiem.addActionListener(this);
        btnthem.addActionListener(this);
        btnsua.addActionListener(this);
        btnxoa.addActionListener(this);
        btnhuy.addActionListener(this);
        btnback.addActionListener(this);
        txtmadetai.addActionListener(this);
    }

    @Override
    public void getDataTimKiemSinhVien(int malop, String ten, String ngaysinh, int gioitinh, String diachi, String sdt, String email) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
