/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.PreSenter.GiaoDucPreSenter;
import Interface.PreSenter.GiaoDucView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Penguin
 */
public class Tiendo extends javax.swing.JFrame
implements  ActionListener,GiaoDucView{
 private GiaoDucPreSenter gd;
   private String User;
   private int maquyen;
    public Tiendo(String U,int ma) {
        initComponents();
        gd=new GiaoDucPreSenter(this);
        gd.HanlerReadDataDeTai();
        HanlerEvents();
        User=U;
        maquyen=ma;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        madetaicombo = new javax.swing.JComboBox<>();
        tgbc = new javax.swing.JTextField();
        tdth = new javax.swing.JTextField();
        nbc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        gc = new javax.swing.JTextArea();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        txttentimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setTitle("Tiến độ");
        jInternalFrame2.setToolTipText("");
        jInternalFrame2.setAutoscrolls(true);
        jInternalFrame2.setDoubleBuffered(true);
        jInternalFrame2.setFocusTraversalPolicyProvider(true);
        jInternalFrame2.setInheritsPopupMenu(true);
        jInternalFrame2.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cập nhật tiến độ");

        jLabel3.setText("Mã đề tài:");
        jLabel3.setToolTipText("");

        jLabel4.setText("Thời gian báo cáo:");

        jLabel5.setText("Tiến độ thực hiện:");

        jLabel6.setText("Người báo cáo:");

        jLabel7.setText("Ghi chú:");

        tgbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbcActionPerformed(evt);
            }
        });

        gc.setColumns(20);
        gc.setRows(5);
        jScrollPane1.setViewportView(gc);

        btnthem.setText("Thêm");

        btnsua.setText("Sửa");

        btnxoa.setText("Xóa");

        btnhuy.setText("Hủy");

        btntimkiem.setText("Tìm Kiếm");

        btnback.setText("Back");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nbc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tdth, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgbc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(madetaicombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addGap(56, 56, 56)
                        .addComponent(btnsua)
                        .addGap(58, 58, 58)
                        .addComponent(btnxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnhuy)
                        .addGap(44, 44, 44))))
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btntimkiem)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(txttentimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnback))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(madetaicombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tgbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tdth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnhuy))
                .addGap(44, 44, 44)
                .addComponent(txttentimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntimkiem)
                .addGap(18, 18, 18)
                .addComponent(btnback))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        try {
            jInternalFrame2.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tgbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgbcActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JTextArea gc;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> madetaicombo;
    private javax.swing.JTextField nbc;
    private javax.swing.JTextField tdth;
    private javax.swing.JTextField tgbc;
    private javax.swing.JTextField txttentimkiem;
    // End of variables declaration//GEN-END:variables


    @Override
    public void OnSucess() {
        JOptionPane.showMessageDialog(rootPane, "Sucess","Thong Bao",1);
    }

    @Override
    public void OnError() {
        JOptionPane.showMessageDialog(rootPane, "Failed","Thong Bao",1);
    }

    @Override
    public void getDataTimKiem(String ten, String truongkhoa, String sdt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
  
    }

    @Override
    public void getDataKhoa(int makhoa, String ten, String truongkhoa, String sdt) {
       madetaicombo.addItem(String.valueOf(makhoa));
    }

    @Override
    public void getDataTimKiemLop(int makhoa, String tenlop) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataLop(int makhoa, int malop, String tenlop) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
    @Override
    public void getDataTimKiemGV(int makhoa, String ten, String ngaysinh, String hocvi, int gioitinh, String diachi, String sdt, String email, String chuyennganh) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataTimKiemTienDo(String maBC, String madetai, String thoigianbaocao, String tiendothuchien, String nguoibaocao, String ghichu) {
        madetaicombo.setSelectedItem(madetai);
        tgbc.setText(thoigianbaocao);
        tdth.setText(tiendothuchien);
        nbc.setText(nguoibaocao);
        gc.setText(ghichu);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btnthem){
            String madt=(String) madetaicombo.getSelectedItem();
            SimpleDateFormat spf=new SimpleDateFormat("yyyy-MM-dd");
            String thoigianbaocao=tgbc.getText().toString().trim();
            String thtd=tdth.getText().toString().trim();
            String nguoibaocao=nbc.getText().toString().trim();
            String ghichu=gc.getText().toString().trim();
            try {
                spf.parse(thoigianbaocao);
                if(thoigianbaocao.length()>0 && thtd.length()>0&& nguoibaocao.length()>0
                        && ghichu.length()>0){
                    gd.HanlerInsertTienDo(madt, thoigianbaocao, ghichu, nguoibaocao, ghichu);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Khong De Trong","Thong Bao",1);
                }
                
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai Dinh Dang","Thong Bao",1);
            }
            
            
        }else if(e.getSource()==btnhuy){
           tgbc.setText(null);tdth.setText(null);
            nbc.setText(null);gc.setText(null);
        }else if(e.getSource()==btnxoa){
            String ten=nbc.getText().toString().trim();
            if(ten.length()>0){
                gd.HanlerDeleteTienDo(ten);
            }
            
        }else if(e.getSource()==btntimkiem){
            String ten=txttentimkiem.getText().toString().trim();
            if(ten.length()>0){
            gd.HanlerTimKiemTienDo(ten);     
            }
           
            
        }else if(e.getSource()==btnsua){
             String madt=(String) madetaicombo.getSelectedItem();
            SimpleDateFormat spf=new SimpleDateFormat("yyyy-MM-dd");
            String thoigianbaocao=tgbc.getText().toString().trim();
            String thtd=tdth.getText().toString().trim();
            String nguoibaocao=nbc.getText().toString().trim();
            String ghichu=gc.getText().toString().trim();
            try {
                spf.parse(thoigianbaocao);
                if(thoigianbaocao.length()>0 && thtd.length()>0&& nguoibaocao.length()>0
                        && ghichu.length()>0){
                    gd.HanlerUpdateTienDo(madt, thoigianbaocao, ghichu, nguoibaocao, ghichu);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Khong De Trong","Thong Bao",1);
                }
                
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Sai Dinh Dang","Thong Bao",1);
            }
        }else if(e.getSource()==btnback){
            new GDmain(User,maquyen).setVisible(true);
            this.dispose();
        }
    }

    private void HanlerEvents() {
        btnthem.addActionListener(this);
        btnsua.addActionListener(this);
        btnxoa.addActionListener(this);
        btnhuy.addActionListener(this);
        btnback.addActionListener(this);
        btntimkiem.addActionListener(this);
    }

    @Override
    public void getDataTimKiemNghiemThu(String mant, String madetai, String tgnt, String tgbd, String tgkt, float kinhphi, String ketluan) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void getDataTimKiemSinhVien(int malop, String ten, String ngaysinh, int gioitinh, String diachi, String sdt, String email) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
